### ISSUE TITLE
I got a ValueError: None values not supported.

### ISSUE THREAD

**Issue by Agent-INF** [jazzsaxmafia/Impainting#6]
I ran train.imagenet.py with img_align_celeba dataset, and I got this error:
Traceback (most recent call last):
  File "src/train.imagenet.py", line 98, in <module>
    grads_vars_G = map(lambda gv: [tf.clip_by_value(gv[0], -10., 10.), gv[1]], grads_vars_G)
  File "src/train.imagenet.py", line 98, in <lambda>
    grads_vars_G = map(lambda gv: [tf.clip_by_value(gv[0], -10., 10.), gv[1]], grads_vars_G)
  File "/home/edward/.local/lib/python2.7/site-packages/tensorflow/python/ops/clip_ops.py", line 55, in clip_by_value
    t = ops.convert_to_tensor(t, name="t")
  File "/home/edward/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 639, in convert_to_tensor
    as_ref=False)
  File "/home/edward/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 704, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/edward/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 113, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/edward/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/edward/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 360, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

**Comment by hhwhbf** [comment]
I have also encountered the same problem.Did you solve the problem?

**Comment by Agent-INF** [comment]
@hhwhbf Sorry, I still didn't solve this.

**Comment by ghazi-f** [comment]
Replace 
`map(lambda gv: [tf.clip_by_value(gv[0], -10., 10.), gv[1]], grads_vars_G)`
by 
`map(lambda gv: gv if gv[0] is None else [tf.clip_by_value(gv[0], -10., 10.), gv[1]], grads_vars_G)`
The optimizer yields None when gradients are null instead of zeroes.

**Comment by Agent-INF** [comment]
@Sora77 It works, thank you very much!

**Comment by hhwhbf** [comment]
@Edward-Lin I take his suggestion,but there still a bug as follows:
```
 File "C:/Users/Administrator/PycharmProjects/untitled1/train.imagenet.py", line 105, in <module>
    train_op_G = optimizer_G.apply_gradients( grads_vars_G )
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\tensorflow\python\training\optimizer.py", line 380, in apply_gradients
    raise ValueError("No variables provided.")
```
Is it convenient for you to send you code to my e-mail:1136288430@qq.com?Thank you very much.
By the way,can you tell me your Python and Tensorflow Version?

**Comment by Agent-INF** [comment]
@hhwhbf  OK, I'm sending my code to you.

**Comment by lizhuorong** [comment]
@Edward-Lin Could you please send your code to me too? I got the same error and I have tried but some other errors arise. My email: 124132545@qq.com

Thanks you!

**Comment by Agent-INF** [comment]
@lizhuorong OK

**Comment by MrWhiteHomeman** [comment]
@Edward-Lin ， I am a student  in Nanjing.  When I run the code , I meet some problems ,  can you send your code to me ? Thank u !!!
my email:  baijianan7gmail.com

**Comment by Edward-Lin** [comment]
@MrWhiteHomeman You may find my code at [https://github.com/Edward-Lin/inpainting](url)

**Comment by Agent-INF** [comment]
@MrWhiteHomeman You may find my code at [https://github.com/Edward-Lin/inpainting](https://github.com/Edward-Lin/inpainting)
