### ISSUE TITLE
ValueError: Variable DIS/bn1/DIS_1/bn1/moments/Squeeze/ExponentialMovingAverage/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

### ISSUE THREAD

**Issue by maryam089** [jazzsaxmafia/Impainting#8]
When I try to train the model for paris street dataset I get that error can anyone help me ?

C:/Users/maryam/PycharmProjects/INPAINTING/src/train.paris_edit.py:52: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  testset = testset.ix[np.random.permutation(len(testset))]
Traceback (most recent call last):
  File "C:/Users/maryam/PycharmProjects/INPAINTING/src/train.paris_edit.py", line 66, in <module>
    adversarial_neg = model.build_adversarial(reconstruction, is_train, reuse=True)
  File "C:\Users\maryam\PycharmProjects\INPAINTING\src\model.py", line 140, in build_adversarial
    bn1 = self.leaky_relu(self.batchnorm(conv1, is_train, name='bn1'))
  File "C:\Users\maryam\PycharmProjects\INPAINTING\src\model.py", line 97, in batchnorm
    ema_apply_op = ema.apply([batch_mean, batch_var])
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\moving_averages.py", line 375, in apply
    colocate_with_primary=(var.op.type in ["Variable", "VariableV2"]))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\slot_creator.py", line 174, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\slot_creator.py", line 149, in create_slot_with_initializer
    dtype)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\slot_creator.py", line 66, in _create_slot_var
    validate_shape=validate_shape)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 367, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 682, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable DIS/bn1/DIS_1/bn1/moments/Squeeze/ExponentialMovingAverage/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

**Comment by MrWhiteHomeman** [comment]
Hello ，I meet this problem，too. Did you solve this problem?

**Comment by Tysonwei** [comment]
Hello ，I meet this problem，too. Did you solve this problem?

**Comment by Tysonwei** [comment]
I meet this problem，too. Did you solve this problem?

**Comment by xhan97** [comment]
Hi, I also meet this problem. Did you solve this problem?

**Comment by Frozenmad** [comment]
Me, too...

**Comment by aditisingh** [comment]
Same here

**Comment by rabiaali95** [comment]
does anyone knows the solution?
